/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package xuongdesktopsu24.views;

import java.awt.CardLayout;

/**
 *
 * @author syn
 */
public class Home extends javax.swing.JFrame {
    private CardLayout cardLayout;
            
    /** Creates new form Home */
    public Home() {
        initComponents();
        cardLayout = (CardLayout) cards.getLayout();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnShowSanPhamView = new javax.swing.JButton();
        btnShowBanHangView = new javax.swing.JButton();
        cards = new javax.swing.JPanel();
        cardSanPham = new javax.swing.JPanel();
        viewSanPham1 = new xuongdesktopsu24.views.ViewSanPham();
        cardBanHang = new javax.swing.JPanel();
        viewBanHang1 = new xuongdesktopsu24.views.ViewBanHang();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 255));

        btnShowSanPhamView.setText("SanPham");
        btnShowSanPhamView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSanPhamViewActionPerformed(evt);
            }
        });

        btnShowBanHangView.setText("BanHang");
        btnShowBanHangView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowBanHangViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowBanHangView)
                    .addComponent(btnShowSanPhamView))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnShowSanPhamView)
                .addGap(38, 38, 38)
                .addComponent(btnShowBanHangView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        cards.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout cardSanPhamLayout = new javax.swing.GroupLayout(cardSanPham);
        cardSanPham.setLayout(cardSanPhamLayout);
        cardSanPhamLayout.setHorizontalGroup(
            cardSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewSanPham1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        cardSanPhamLayout.setVerticalGroup(
            cardSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewSanPham1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        cards.add(cardSanPham, "cardSanPham");

        javax.swing.GroupLayout cardBanHangLayout = new javax.swing.GroupLayout(cardBanHang);
        cardBanHang.setLayout(cardBanHangLayout);
        cardBanHangLayout.setHorizontalGroup(
            cardBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewBanHang1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        cardBanHangLayout.setVerticalGroup(
            cardBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewBanHang1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        cards.add(cardBanHang, "cardBanHang");

        jSplitPane1.setRightComponent(cards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowSanPhamViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSanPhamViewActionPerformed
        cardLayout.show(cards, "cardSanPham");
    }//GEN-LAST:event_btnShowSanPhamViewActionPerformed

    private void btnShowBanHangViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowBanHangViewActionPerformed
        cardLayout.show(cards, "cardBanHang");
    }//GEN-LAST:event_btnShowBanHangViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowBanHangView;
    private javax.swing.JButton btnShowSanPhamView;
    private javax.swing.JPanel cardBanHang;
    private javax.swing.JPanel cardSanPham;
    private javax.swing.JPanel cards;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private xuongdesktopsu24.views.ViewBanHang viewBanHang1;
    private xuongdesktopsu24.views.ViewSanPham viewSanPham1;
    // End of variables declaration//GEN-END:variables

}
